version: '3.8'

services:
  ds:
    build:
      context: .
    container_name: graphrunner-ds
    environment:
      - USE_KAFKA=true
      - KAFKA_MODE=docker
      - KAFKA_BROKER_DOCKER=kafka:9092
      - KAFKA_TOPIC=graphrunner.ingest
      - TEMPLATE_PATH=./templates/sample-template.json
      - SEND_INTERVAL_MS=500
    volumes:
      - ./templates:/app/templates
    restart: always
    networks:
      - graphrunner-net

networks:
  graphrunner-net:
    external: true
